config/routes.rb
Rails.application.routes.draw do
  root controller: :welcome, action: :index
  get "about", to: "about#index"
  resources :articles, only: [:show, :index, :new, :create, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
 class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 320}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


  def show
    @article = Article.find(params[:id])
  end

  def index
    @article = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end


  def create
    @article = Article.new(params.require(:article).permit(:title, :description))
    if @article.save
      flash[:notice] = 'Article was created successfully'
      redirect_to @article
    else
      render 'new'
    end
  end


  def update
    @article = Article.find(params[:id])
    if @article.update(params.require(:article).permit(:title, :description))
        flash[:notice] = "Article was updated successfully"
        redirect_to @article
    else
        render 'edit'
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
    <% @article.errors.full_messages.each do|msg| %>
      <li> <%= msg %> </li>
    <% end  %>
  </ul>
<% end %>

<h1></h1>

<%= form_with(model: @article, local: true)  do |f| %>
  <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
  </p>


  <p>
      <%= f.label :description %><br>
      <%= f.text_area :description %>
  </p>


  <p>
      <%= f.submit %>
  </p>
<% end %>

app/views/articles/index.html.erb
<h1>Articles Listing page</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Actions</th>
    <tr>
  </thead>


    <tbody>
      <% @article.each do |article| %>
      <tr>
        <td><%= article.title%></td>
        <td><%= article.description%></td>
        <td>Placeholder</td>
      </tr>
      <% end %>
    </tbody>


</table>

app/views/articles/new.html.erb
<h1>Create a new Article</h1>

<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
    <% @article.errors.full_messages.each do|msg| %>
      <li> <%= msg %> </li>
    <% end  %>
  </ul>
<% end %>

<h1></h1>

<%= form_with scope: :article, url: articles_path, local: true do |f| %>
  <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
  </p>


  <p>
      <%= f.label :description %><br>
      <%= f.text_area :description %>
  </p>


  <p>
      <%= f.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>
<p>Title: <%= @article.title %></p>
<p>Description: <%= @article.description %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= msg %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcomeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee</h1>